# Generated by Django 5.2.6 on 2025-09-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Toyota'), (2, 'Honda'), (3, 'Ford'), (4, 'Chevrolet'), (5, 'Nissan'), (6, 'Volkswagen'), (7, 'Hyundai'), (8, 'Kia'), (9, 'Mazda'), (10, 'Subaru')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'Vermelho'), (2, 'Azul'), (3, 'Preto'), (4, 'Branco'), (5, 'Cinza'), (6, 'Prata'), (7, 'Verde'), (8, 'Amarelo')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Elétrico'), (5, 'Híbrido')])),
            ],
        ),
    ]
