# Generated by Django 5.2.7 on 2025-10-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('AUDI', 'AUDI'), ('BMW', 'BMW'), ('CHEVROLET', 'CHEVROLET'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('VOLKSWAGEN', 'VOLKSWAGEN')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(choices=[('VERMELHO', 'VERMELHO'), ('BRANCO', 'BRANCO'), ('AZUL', 'AZUL'), ('PRETO', 'PRETO'), ('CINZA', 'CINZA'), ('PRATA', 'PRATA')], max_length=20)),
                ('combustivel', models.CharField(choices=[('ETANOL', 'ETANOL'), ('DIESEL', 'DIESEL'), ('FLEX', 'FLEX'), ('GASOLINA', 'GASOLINA')], max_length=20)),
                ('foto', models.ImageField(blank=True, help_text='Foto do veículo', null=True, upload_to='veiculos/')),
            ],
        ),
    ]
