# Generated by Django 4.2.11 on 2025-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
