# Generated by Django 4.2.11 on 2025-10-16 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('marca', models.CharField(choices=[('AUDI', 'AUDI'), ('BMW', 'BMW'), ('CHEVROLET', 'CHEVROLET'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('VOLKSWAGEN', 'VOLKSWAGEN')], max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('km', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('cambio', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático'), ('CVT', 'CVT')], max_length=20, verbose_name='Câmbio')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], max_length=20, verbose_name='Combustível')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('cor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cor')),
                ('imagem_principal', models.ImageField(blank=True, help_text='Imagem principal do veículo', null=True, upload_to='anuncios/', verbose_name='Imagem Principal')),
                ('imagens_adicionais', models.JSONField(blank=True, help_text='URLs das imagens adicionais em formato JSON', null=True, verbose_name='Imagens Adicionais')),
                ('cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('vendido', 'Vendido')], default='ativo', max_length=10, verbose_name='Status')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Anúncio de Carro',
                'verbose_name_plural': 'Anúncios de Carros',
                'db_table': 'anuncios_carros',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
