# Generated by Django 4.2.11 on 2025-10-16 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciocarro',
            name='cor',
            field=models.CharField(blank=True, choices=[('Vermelho', 'Vermelho'), ('Branco', 'Branco'), ('Azul', 'Azul'), ('Preto', 'Preto'), ('Cinza', 'Cinza'), ('Prata', 'Prata')], max_length=30, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='anunciocarro',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='anunciocarro',
            name='imagens_adicionais',
            field=models.JSONField(blank=True, null=True, verbose_name='Imagens Adicionais'),
        ),
        migrations.AlterField(
            model_name='anunciocarro',
            name='marca',
            field=models.CharField(choices=[('AUDI', 'Audi'), ('BMW', 'BMW'), ('CHEVROLET', 'Chevrolet'), ('FERRARI', 'Ferrari'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('VOLKSWAGEN', 'Volkswagen')], max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='anunciocarro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
